version: "2.4"
services:
  minimalist-web-notepad:
    build: .
    container_name: minimalist-web-notepad
    restart: always
    ports:
     - "8632:8632"
    volumes:
     - minimalist-web-notepad:/var/www/html/_tmp

volumes:
  minimalist-web-notepad:
